### ISSUE TITLE
Sort by number of profanities doesn't work

### ISSUE THREAD

**Issue by ericbf** [jbrower95/Explicitor#3]
I commented out the part that plays the success sound just to test it. The program works just as expected, but when it finished, sort by number of profanities doesn't work, though the other columns do work.

**Comment by jbrower95** [comment]
Fantastic! I think the sort failing has to do with storing that table entry
as a string and not an integer... i'll have to take a look

**Comment by ericbf** [comment]
It’s been ten years now. Just closing this.
